
package com.gk.htc.sendMT.VasVTE.HTC;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "Exception", targetNamespace = "http://impl.bulkSms.ws/")
public class Exception_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private com.gk.htc.sendMT.VasVTE.HTC.Exception faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public Exception_Exception(String message, com.gk.htc.sendMT.VasVTE.HTC.Exception faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public Exception_Exception(String message, com.gk.htc.sendMT.VasVTE.HTC.Exception faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.gk.htc.sendMT.VasVTE.HTC.Exception
     */
    public com.gk.htc.sendMT.VasVTE.HTC.Exception getFaultInfo() {
        return faultInfo;
    }

}
