
package com.gk.htc.sendMT.VasVTE.HTC;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WsBulkSms", targetNamespace = "http://impl.bulkSms.ws/", wsdlLocation = "http://125.235.40.125:8985/WS?wsdl")
public class WsBulkSms_Service
    extends Service
{

    private final static URL WSBULKSMS_WSDL_LOCATION;
    private final static WebServiceException WSBULKSMS_EXCEPTION;
    private final static QName WSBULKSMS_QNAME = new QName("http://impl.bulkSms.ws/", "WSBulkSms");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://125.235.40.125:8985/WS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSBULKSMS_WSDL_LOCATION = url;
        WSBULKSMS_EXCEPTION = e;
    }

    public WsBulkSms_Service() {
        super(__getWsdlLocation(), WSBULKSMS_QNAME);
    }

    public WsBulkSms_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSBULKSMS_QNAME, features);
    }

    public WsBulkSms_Service(URL wsdlLocation) {
        super(wsdlLocation, WSBULKSMS_QNAME);
    }

    public WsBulkSms_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSBULKSMS_QNAME, features);
    }

    public WsBulkSms_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsBulkSms_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsBulkSms
     */
    @WebEndpoint(name = "WsBulkSmsPort")
    public WsBulkSms getWsBulkSmsPort() {
        return super.getPort(new QName("http://impl.bulkSms.ws/", "WsBulkSmsPort"), WsBulkSms.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsBulkSms
     */
    @WebEndpoint(name = "WsBulkSmsPort")
    public WsBulkSms getWsBulkSmsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.bulkSms.ws/", "WsBulkSmsPort"), WsBulkSms.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSBULKSMS_EXCEPTION!= null) {
            throw WSBULKSMS_EXCEPTION;
        }
        return WSBULKSMS_WSDL_LOCATION;
    }

}
