
package com.gk.htc.sendMT.MFS.ANTIT;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AntitApi", targetNamespace = "http://webservice.agentsms/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AntitApi {


    /**
     * 
     * @param pass
     * @param msisdn
     * @param brandname
     * @param msgbody
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendMT")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SendMT", targetNamespace = "http://webservice.agentsms/", className = "com.gk.htc.sendMT.MFS.ANTIT.SendMT")
    @ResponseWrapper(localName = "SendMTResponse", targetNamespace = "http://webservice.agentsms/", className = "com.gk.htc.sendMT.MFS.ANTIT.SendMTResponse")
    @Action(input = "http://webservice.agentsms/AntitApi/SendMTRequest", output = "http://webservice.agentsms/AntitApi/SendMTResponse")
    public String sendMT(
        @WebParam(name = "msisdn", targetNamespace = "")
        String msisdn,
        @WebParam(name = "brandname", targetNamespace = "")
        String brandname,
        @WebParam(name = "msgbody", targetNamespace = "")
        String msgbody,
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass);

}
