package com.gk.htc.sendMT.MFS.ANTIT;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.6-1b01 Generated
 * source version: 2.2
 *
 */
@WebServiceClient(name = "AntitApi", targetNamespace = "http://webservice.agentsms/", wsdlLocation = "http://103.63.109.195:8484/AgentSMS/AntitApi?wsdl")
public class AntitApi_Service
        extends Service {

    private final static URL ANTITAPI_WSDL_LOCATION;
    private final static WebServiceException ANTITAPI_EXCEPTION;
    private final static QName ANTITAPI_QNAME = new QName("http://webservice.agentsms/", "AntitApi");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://103.63.109.195:8484/AgentSMS/AntitApi?wsdl");
//            System.out.println("URL: http://103.63.109.195:8484/AgentSMS/AntitApi?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ANTITAPI_WSDL_LOCATION = url;
        ANTITAPI_EXCEPTION = e;
    }

    public AntitApi_Service() {
        super(__getWsdlLocation(), ANTITAPI_QNAME);
    }

    public AntitApi_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ANTITAPI_QNAME, features);
    }

    public AntitApi_Service(URL wsdlLocation) {
        super(wsdlLocation, ANTITAPI_QNAME);
    }

    public AntitApi_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ANTITAPI_QNAME, features);
    }

    public AntitApi_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AntitApi_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return returns AntitApi
     */
    @WebEndpoint(name = "AntitApiPort")
    public AntitApi getAntitApiPort() {
        return super.getPort(new QName("http://webservice.agentsms/", "AntitApiPort"), AntitApi.class);
    }

    /**
     *
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to
     * configure on the proxy. Supported features not in the
     * <code>features</code> parameter will have their default values.
     * @return returns AntitApi
     */
    @WebEndpoint(name = "AntitApiPort")
    public AntitApi getAntitApiPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.agentsms/", "AntitApiPort"), AntitApi.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ANTITAPI_EXCEPTION != null) {
            throw ANTITAPI_EXCEPTION;
        }
        return ANTITAPI_WSDL_LOCATION;
    }

}
